
{% set name = "celery" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/celery-{{ version }}.tar.gz
  sha256: 504a19140e8d3029d5acad88330c541d4c3f64c789d85f94756762d8bca7e706
build:
  noarch: python
  entry_points:
    - celery = celery.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - pytest
  run:
    - python >=3.10
    - billiard >=4.2.0,<5.0
    - kombu >=5.3.4,<6.0
    - vine >=5.1.0,<6.0
    - click >=8.1.2,<9.0
    - click-didyoumean >=0.3.0
    - click-repl >=0.2.0
    - click-plugins >=1.1.1
    - importlib-metadata >=3.6
    - backports.zoneinfo >=0.2.1
    # Source uses tzdata>=2022.7, python-tzdata and tzdata are available on conda-forge, python-tzdata is the correct conda package to use
    - python-tzdata >=2022.7
    - python-dateutil >=2.8.2

test:
  requires:
    - dnspython
    - pymongo
    - pytest
    - pytest-celery
    - pytest-subtests
    - pytest-timeout
    - pytest-click
    - boto3>=1.9.178
    - moto>=2.2.6
    - pip
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    # Requires sqlalchemy but it's an optional dependency
    # - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - pip check
    - celery --version
    - celery --help
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - chrisburr
    - efiop
    - kwilcox
    - sodre
